wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692328167.531957
    t:
      1:
      - 49
      - 55
      - 86
      - 95
      - 105
      2:
      - 49
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.9.6
      5: 0.15.8
      8:
      - 5
      9:
        2: langchain
